#!/bin/bash

### BEGIN INIT INFO
# Provides: fake-hwclock
# Required-Start: $local_fs
# Should-Start:
# Required-Stop: $local_fs
# Should-Stop:
# Default-Start: S
# Default-Stop: 0 6
# Short-Description: Restores clock to shutdown time
# Description: Restores clock to shutdown time
### END INIT INFO

case "${1}" in
	start)
		savedtime=$(stat -c %Y "$0")
		if [ $(date +%s) -lt ${savedtime} ]; then
			echo "Restoring saved system time"
			date -s @${savedtime}
		else
			echo "Not restoring old system time"
		fi
	;;
	stop)
		echo "Saving current time."
		touch "${0}"
	;;
	*)
		echo "Usage: ${0} {start|stop}"
		exit 1
		;;
esac
