#!/bin/sh

### BEGIN INIT INFO
# Provides: switch-cpu-governor
# Required-Start: $local_fs
# Should-Start:
# Required-Stop:
# Should-Stop: $local_fs
# Default-Start: S
# Default-Stop:
# Short-Description: Switches to ondemand governor
# Description: Switches to ondemand governor
### END INIT INFO

source /lib/lsb/init-functions

case "${1}" in
	start)	log_info_msg "Switching to ondemand scaling governor..."
		SYS_CPUFREQ_GOVERNOR=/sys/devices/system/cpu/cpu0/cpufreq/scaling_governor
		if [ -e ${SYS_CPUFREQ_GOVERNOR} ]; then
			echo "ondemand" > ${SYS_CPUFREQ_GOVERNOR}
			echo 50 > /sys/devices/system/cpu/cpufreq/ondemand/up_threshold
			echo 100000 > /sys/devices/system/cpu/cpufreq/ondemand/sampling_rate
			echo 50 > /sys/devices/system/cpu/cpufreq/ondemand/sampling_down_factor
		fi
		;;
	status)	SYS_CPUFREQ_GOVERNOR=/sys/devices/system/cpu/cpu0/cpufreq/scaling_governor
			[ -e ${SYS_CPUFREQ_GOVERNOR} ] && cat ${SYS_CPUFREQ_GOVERNOR}
		;;
	*)	echo "Usage: ${0} {start|status}"; exit 1; ;;
esac
exit 0
